export enum FeeErrors {
  ERROR_SYSTEM_FEE_NOT_FOUND = 'ERROR_SYSTEM_FEE_NOT_FOUND',
  ERROR_EXISTED_SYSTEM_FEE_CURRENT = 'ERROR_EXISTED_SYSTEM_FEE_CURRENT',
  ERROR_SYSTEM_FEE_NOT_WORKING = 'ERROR_SYSTEM_FEE_NOT_WORKING',
  ERROR_ONE_OR_MORE_USER_WAS_APPLY = 'ERROR_ONE_OR_MORE_USER_WAS_APPLY',
  ERROR_EXISTED_OWN_FEEE = 'ERROR_EXISTED_OWN_FEEE',
  ERROR_OWN_FEE_NOT_FOUND = 'ERROR_OWN_FEE_NOT_FOUND',
  ERROR_EXISTED_OWN_FEE_USING = 'ERROR_EXISTED_OWN_FEE_USING',
}
