export enum FeeErrors {
  ERROR_SYSTEM_FEE_NOT_FOUND = 'ERROR_SYSTEM_FEE_NOT_FOUND',
  ERROR_EXIST_SYSTEM_FEE_CURRENT = 'ERROR_EXIST_SYSTEM_FEE_CURRENT',
  ERROR_SYSTEM_FEE_NOT_WORKING = 'ERROR_SYSTEM_FEE_NOT_WORKING',
  ERROR_ONE_OR_MORE_USER_WAS_APPLY = 'ERROR_ONE_OR_MORE_USER_WAS_APPLY',
}
