export enum OtpErrors {
  ERROR_MAX_GENERATE_OTP = 'ERROR_MAX_GENERATE_OTP',
  ERROR_OTP_EMAIL_NOT_FOUND = 'ERROR_OTP_EMAIL_NOT_FOUND',
  ERROR_OTP_EMAIL_INVALID = 'ERROR_OTP_EMAIL_INVALID',
  ERROR_OTP_EMAIL_EXPIRED = 'ERROR_OTP_EMAIL_EXPIRED',
}
