export enum UserErrors {
  ERROR_EXISTED_USER = 'ERROR_EXISTED_USER',
  ERROR_USER_NOT_EXISTTING = 'ERROR_USER_NOT_EXISTTING',
  ERROR_PASSWORD_FAIL = 'ERROR_PASSWORD_FAIL',
  ERROR_ONE_OR_MORE_USER_NOT_FOUND = 'ERROR_ONE_OR_MORE_USER_NOT_FOUND',
  ERROR_YOU_CAN_NOT_ACCESS_TO_RESOURCE = 'ERROR_YOU_CAN_NOT_ACCESS_TO_RESOURCE',
}
