export enum QUEUEU_NAME {
  FIRST_QUEUE = 'FIRST_QUEUE',
}

export enum EXCHANEL_NAME {
  ACCOUNT_EXCHANEL_NAME = 'ACCOUNT_EXCHANEL_NAME',
}

export enum ROUTER_KEY {
  ACCOUNT_ROUTER_KEY = 'ACCOUNT_ROUTER_KEY',
}
